### ISSUE TITLE
[warning] The "block_content:ceb6b542-d0c7-4a02-9ad0-7095f4adf62a" was not found

### ISSUE THREAD

**Issue by hagi60** [bkenro/ddrecipe-demo#2]
drush site:installで
[warning] The "block_content:ceb6b542-d0c7-4a02-9ad0-7095f4adf62a" was not found
というメッセージが出ましたが、インストールは無事できました。
問題ないものでしょうか？

**Comment by bkenro** [comment]
はい、構成設定の読み込み時にブロックコンテンツが見つからないために表示される警告ですが、その後、Default Content モジュールによってインポートされるので実用上は問題ないと思います。

**Comment by hagi60** [comment]
ありがとうございました。
